clc;
fs = 8000;
t=(0:0.2*fs)/fs;
fm=100;
signal = sin(2*pi*fm*t);
fc = 500;
initialPhase = 0;
subplot(4,1,1);
plot(t,signal);
title("Message Signal with fm=100 HZ");
xlabel("Time");
ylabel("Amplitude");
c=cos(2*pi*fc*t);
subplot(4,1,2);
plot(t,c);
title("Carrier Signal with fc=500 HZ");
xlabel("Time");
ylabel("Amplitude");
lowerSidebandSignal=ssbmod(signal,fc,fs,initialPhase);
subplot(4,1,3);
plot(t,lowerSidebandSignal);
title("LSB SSB Modulated Signal");
xlabel("Time");
ylabel("Amplitude");
demodsignal=ssbdemod(lowerSidebandSignal,fc,fs);
subplot(4,1,4);
plot(t,demodsignal);
title("Demodulated Signal");
xlabel("Time");
ylabel("Amplitude");
